### PR TITLE
Add allowed fixmes for hhvm 4.62

### PR DESCRIPTION
**Pull request by lexidor**
Running Fred's jq script

Co-authored-by: Fred Emmott <fe@fb.com>

### CODE REVIEW

**Comment by lexidor** [comment]
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - hhvm/hacktest v2.0.0 requires hhvm/type-assert ^3.2 -> satisfiable by hhvm/type-assert[v3.2.0, v3.2.1, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.3.0, v3.3.1, v3.3.2, v3.4.0, v3.4.1, v3.4.2, v3.5.0, v3.5.1, v3.6.0, v3.6.1, v3.6.2, v3.6.3, v3.6.4, v3.6.5, v3.7.0, v3.7.1, v3.7.3].
    - hhvm/hacktest v2.0.1 requires hhvm/type-assert ^3.2 -> satisfiable by hhvm/type-assert[v3.2.0, v3.2.1, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.3.0, v3.3.1, v3.3.2, v3.4.0, v3.4.1, v3.4.2, v3.5.0, v3.5.1, v3.6.0, v3.6.1, v3.6.2, v3.6.3, v3.6.4, v3.6.5, v3.7.0, v3.7.1, v3.7.3].
    - Can only install one of: hhvm/type-assert[v3.3.0, 4.x-dev].
```

Hacktest for hhvm 4.30 and 4.32 specify that they need typeassert ^3._`, meaning they won't use 4.0-dev , so we must install type-assert to test type-assert (which would be a typeerror anyway, because duplicate definitions) and the constraints can not be resolved.

**Comment by fredemmott** [comment]
Probably time to update the minimum version and go to type-assert 4.1 then - probably 4.56 as the lower bound

**Comment by lexidor** [comment]
This is gonna be /fun/ next release.
I know that we don't want to expose this to devs, since it is an implementation detail, but what about unhiding `\HH\is_varray()` and `\HH\is_darray()`?
You kinda need it if `varray_or_darray<_> === varray<_>` is always false in hhvm 4.63.

```
31) Facebook\TypeAssert\TypeStructureTest::testValidCoercion with data set
#varray<int> as varray_or_darray<int>

Failed asserting that array (
  0 => 123,
) is equal to array (
  0 => 123,
)
```

**Comment by fredemmott** [comment]
Replaced by #54

**Pull request closed without merging**
